import { ThemeConfig } from './types';

export const TEMPLATE_01_UBER_MINIMAL: ThemeConfig = {
  id: 'uber-minimal',
  name: 'Qual a sua dor? (Oficial)',
  tagline: 'Fundo branco puro, preto profundo e lilás neon vibrante',
  description: 'Identidade visual oficial da marca. Branco puro, botões pretos de alto contraste e destaques em lilás neon.',
  version: 2,
  typography: {
    headingFont: 'Plus Jakarta Sans',
    bodyFont: 'Plus Jakarta Sans',
    titleDesktopSize: 58,
    titleMobileSize: 38,
    titleWeight: 800,
    titleLineHeight: 1.05,
    titleLetterSpacing: '-0.035em',
    subtitleDesktopSize: 22,
    subtitleMobileSize: 18,
    subtitleWeight: 700,
    subtitleLineHeight: 1.25,
    subtitleLetterSpacing: '-0.02em',
    cardTitleSize: 24,
    cardTitleWeight: 800,
    cardTextSize: 14,
    cardTextWeight: 500,
    cardTextLineHeight: 1.45,
    buttonTextSize: 14,
    buttonTextWeight: 700,
    buttonLetterSpacing: '-0.01em',
    badgeSize: 11,
    badgeWeight: 700,
    footerSize: 12,
  },
  colors: {
    background: '#eaf4ff',
    cardBackground: '#ffffff',
    cardBackgroundHover: '#faf5ff',
    textPrimary: '#09090b',
    textSecondary: '#52525b',
    accent: '#a855f7',
    accentMuted: '#f3e8ff',
    buttonBackground: '#09090b',
    buttonText: '#ffffff',
    buttonHoverBackground: '#7e22ce',
    border: '#e4e4e7',
    badgeBackground: '#faf5ff',
    badgeText: '#7c3aed',
    iconBoxBackground: '#09090b',
    iconColor: '#c084fc',
    isDark: false,
  },
  layout: {
    maxWidth: 920,
    topSpacing: 48,
    heroSpacing: 40,
    cardGap: 24,
    cardPadding: 32,
    borderRadius: 24,
    borderWidth: 1,
  },
  cards: {
    borderRadius: 24,
    borderWidth: 1,
    shadow: 'xs',
    iconSize: 26,
    hoverLift: true,
  },
  buttons: {
    height: 52,
    borderRadius: 16,
    paddingX: 20,
    arrowStyle: 'box',
    shadow: 'xs',
    hoverEffect: 'lift',
  },
  positions: {
    heroAlign: 'center',
    cardsLayout: 'grid',
    cardsOrder: 'physical_first',
    sectionOrder: 'hero_search_cards',
    buttonsAlign: 'stretch',
    searchPosition: 'above_cards',
    headerLayout: 'standard',
  },
  content: {
    heroSubtitle: 'Conta pra gente o que está pegando: pode ser uma dor no corpo ou um perrengue do dia a dia. A gente te ajuda a resolver sem enrolação.',
    searchTitle: 'O que você precisa resolver agora?',
    searchSubtitle: 'Escreva com suas próprias palavras ou escolha um caso rápido:',
    searchPlaceholder: 'Ex: dor nas costas, perdi a chave de casa, pneu furou, dentista urgente...',
    searchButtonText: 'Resolver direto',
  },
};

export const TEMPLATE_02_NEO_STARTUP: ThemeConfig = {
  id: 'neo-startup',
  name: 'Neo Startup',
  tagline: 'Visual contemporâneo e dinâmico de tecnologia recente',
  description: 'Grandes títulos, microinterações, tipografia moderna e cards com presença marcante.',
  version: 1,
  typography: {
    headingFont: 'Sora',
    bodyFont: 'Plus Jakarta Sans',
    titleDesktopSize: 64,
    titleMobileSize: 40,
    titleWeight: 800,
    titleLineHeight: 1.02,
    titleLetterSpacing: '-0.04em',
    subtitleDesktopSize: 24,
    subtitleMobileSize: 19,
    subtitleWeight: 700,
    subtitleLineHeight: 1.25,
    subtitleLetterSpacing: '-0.025em',
    cardTitleSize: 26,
    cardTitleWeight: 800,
    cardTextSize: 15,
    cardTextWeight: 500,
    cardTextLineHeight: 1.45,
    buttonTextSize: 15,
    buttonTextWeight: 800,
    buttonLetterSpacing: '0em',
    badgeSize: 11,
    badgeWeight: 800,
    footerSize: 12,
  },
  colors: {
    background: '#f8fafc',
    cardBackground: '#ffffff',
    cardBackgroundHover: '#f1f5f9',
    textPrimary: '#020617',
    textSecondary: '#475569',
    accent: '#3b82f6',
    accentMuted: '#dbeafe',
    buttonBackground: '#020617',
    buttonText: '#ffffff',
    buttonHoverBackground: '#0f172a',
    border: '#e2e8f0',
    badgeBackground: '#f1f5f9',
    badgeText: '#1e293b',
    iconBoxBackground: '#e0f2fe',
    iconColor: '#0284c7',
    isDark: false,
  },
  layout: {
    maxWidth: 960,
    topSpacing: 52,
    heroSpacing: 44,
    cardGap: 24,
    cardPadding: 32,
    borderRadius: 28,
    borderWidth: 1,
  },
  cards: {
    borderRadius: 28,
    borderWidth: 1,
    shadow: 'sm',
    iconSize: 28,
    hoverLift: true,
  },
  buttons: {
    height: 54,
    borderRadius: 18,
    paddingX: 24,
    arrowStyle: 'classic',
    shadow: 'sm',
    hoverEffect: 'lift',
  },
  positions: {
    heroAlign: 'center',
    cardsLayout: 'grid',
    cardsOrder: 'problem_first',
    sectionOrder: 'hero_cards_search',
    buttonsAlign: 'center',
    searchPosition: 'above_cards',
    headerLayout: 'centered',
    headerSupplierPosition: 'none',
  },
  content: {
    headerBrandPrefix: '',
    headerBrandHighlight: 'NEO',
    headerBadgeVisible: true,
    headerBadgeText: '',
    heroBadgeText: 'Inovação',
    heroBadgeSecondaryText: 'Sem Login',
    heroTitlePrefix: 'Qual é a',
    heroTitleHighlight: 'sua dor?',
    heroSubtitle: 'Tecnologia avançada para detectar e resolver problemas na ponta do clique. Rápido, preciso, sem complicação.',
    cardPhysicalTitle: 'Dor Física 2.0',
    cardPhysicalDesc: 'Corpo, muscular, coluna, cabeça ou desconforto geral. Diagnóstico inteligente.',
    cardPhysicalBadge: 'AI Powered',
    cardPhysicalButton: 'Analisar com IA',
    cardProblemTitle: 'Dor de Problema',
    cardProblemDesc: 'Emergência, carro, casa ou rotina. Solução direta com tecnologia.',
    cardProblemBadge: 'Real-time',
    cardProblemButton: 'Resolver AGORA',
    searchTitle: 'Soluções com tecnologia de ponta',
    searchSubtitle: 'Digite seu problema ou escolha um caso rápido:',
    searchPlaceholder: 'Ex: dor nas costas, pneu furou, dente urgente, vazamento...',
    searchButtonText: 'Resolver',
  },
  visibility: {
    showHeaderBrand: true,
    showHeaderBadge: false,
    showHeaderSupplierBtn: false,
    showMascotsGlobal: false,
    showMascotHero: false,
    showMascotCards: false,
    showHeroBadge: true,
    showHeroTitle: true,
    showHeroSubtitle: true,
    showCardPhysicalBadge: true,
    showCardProblemBadge: true,
  },
  heroLogo: {
    frameStyle: 'card',
    size: 140,
    floatingAnimation: false,
    pulseEffect: false,
  },
};

export const TEMPLATE_03_EDITORIAL_PREMIUM: ThemeConfig = {
  id: 'editorial-premium',
  name: 'Editorial Premium',
  tagline: 'Refinamento de revista, respiro amplo e precisão estética',
  description: 'Espaço generoso em branco, tipografia elegante sem serifa, composição assimétrica e acabamento nobre.',
  version: 1,
  typography: {
    headingFont: 'DM Sans',
    bodyFont: 'DM Sans',
    titleDesktopSize: 56,
    titleMobileSize: 36,
    titleWeight: 700,
    titleLineHeight: 1.08,
    titleLetterSpacing: '-0.03em',
    subtitleDesktopSize: 22,
    subtitleMobileSize: 18,
    subtitleWeight: 500,
    subtitleLineHeight: 1.35,
    subtitleLetterSpacing: '-0.01em',
    cardTitleSize: 22,
    cardTitleWeight: 700,
    cardTextSize: 14,
    cardTextWeight: 400,
    cardTextLineHeight: 1.55,
    buttonTextSize: 13,
    buttonTextWeight: 600,
    buttonLetterSpacing: '0.04em',
    badgeSize: 11,
    badgeWeight: 600,
    footerSize: 11,
  },
  colors: {
    background: '#fcfbf9',
    cardBackground: '#ffffff',
    cardBackgroundHover: '#fbf8f3',
    textPrimary: '#1a1917',
    textSecondary: '#6e6962',
    accent: '#d97706',
    accentMuted: '#fef3c7',
    buttonBackground: '#1a1917',
    buttonText: '#ffffff',
    buttonHoverBackground: '#2d2b27',
    border: '#edebe8',
    badgeBackground: '#f3efe9',
    badgeText: '#4d4841',
    iconBoxBackground: '#f4ede4',
    iconColor: '#854d0e',
    isDark: false,
  },
  layout: {
    maxWidth: 900,
    topSpacing: 60,
    heroSpacing: 48,
    cardGap: 24,
    cardPadding: 36,
    borderRadius: 20,
    borderWidth: 1,
  },
  cards: {
    borderRadius: 20,
    borderWidth: 1,
    shadow: 'xs',
    iconSize: 24,
    hoverLift: true,
  },
  buttons: {
    height: 48,
    borderRadius: 12,
    paddingX: 20,
    arrowStyle: 'subtle',
    shadow: 'none',
    hoverEffect: 'darken',
  },
  positions: {
    heroAlign: 'center',
    cardsLayout: 'stack',
    cardsOrder: 'physical_first',
    sectionOrder: 'hero_search_cards',
    buttonsAlign: 'center',
    searchPosition: 'above_cards',
    headerLayout: 'minimal',
    headerSupplierPosition: 'none',
  },
  content: {
    headerBrandPrefix: 'QUAL',
    headerBrandHighlight: 'É A SUA DOR?',
    headerBadgeVisible: false,
    heroBadgeText: 'Editorial',
    heroBadgeSecondaryText: '',
    heroTitlePrefix: '',
    heroTitleHighlight: 'Respeite seu tempo',
    heroSubtitle: 'Respire. Nosso conteúdo é curado com precisão editorial. Cada solução é selecionada e refinada.',
    cardPhysicalTitle: 'Fisioterapia',
    cardPhysicalDesc: 'Dores musculares, postura, coluna vertebral. Avaliação clínica refinada.',
    cardPhysicalBadge: 'Especializada',
    cardPhysicalButton: 'Ver técnicas',
    cardProblemTitle: 'Soluções',
    cardProblemDesc: 'Doações, custos, rotina. Soluções práticas e testadas.',
    cardProblemBadge: 'Premium',
    cardProblemButton: 'Ver soluções',
    searchTitle: 'Busca editorial refinada',
    searchSubtitle: 'Pesquise com precisão, filtrando por relevância.',
    searchPlaceholder: 'Ex: dor ciática, encanador 24h, remédio...',
    searchButtonText: 'Pesquisar',
  },
  visibility: {
    showHeaderBrand: true,
    showHeaderBadge: false,
    showHeaderSupplierBtn: false,
    showMascotsGlobal: false,
    showMascotHero: false,
    showMascotCards: false,
    showHeroBadge: true,
    showHeroTitle: true,
    showHeroSubtitle: true,
  },
  heroLogo: {
    frameStyle: 'none',
    size: 110,
    floatingAnimation: false,
    pulseEffect: false,
  },
};

export const TEMPLATE_04_BOLD_IMPACT: ThemeConfig = {
  id: 'bold-impact',
  name: 'Bold / Impact',
  tagline: 'Títulos enormes, alto contraste e impossível de ignorar',
  description: 'Criado para capturar a atenção imediata, especialmente para motoristas e passageiros escaneando o QR Code.',
  version: 1,
  typography: {
    headingFont: 'Montserrat',
    bodyFont: 'Plus Jakarta Sans',
    titleDesktopSize: 68,
    titleMobileSize: 44,
    titleWeight: 900,
    titleLineHeight: 0.98,
    titleLetterSpacing: '-0.045em',
    subtitleDesktopSize: 26,
    subtitleMobileSize: 20,
    subtitleWeight: 800,
    subtitleLineHeight: 1.2,
    subtitleLetterSpacing: '-0.02em',
    cardTitleSize: 28,
    cardTitleWeight: 900,
    cardTextSize: 15,
    cardTextWeight: 600,
    cardTextLineHeight: 1.4,
    buttonTextSize: 16,
    buttonTextWeight: 900,
    buttonLetterSpacing: '-0.01em',
    badgeSize: 12,
    badgeWeight: 900,
    footerSize: 12,
  },
  colors: {
    background: '#ffffff',
    cardBackground: '#f8f8f8',
    cardBackgroundHover: '#f0f0f0',
    textPrimary: '#000000',
    textSecondary: '#404040',
    accent: '#eab308',
    accentMuted: '#fef9c3',
    buttonBackground: '#000000',
    buttonText: '#ffffff',
    buttonHoverBackground: '#262626',
    border: '#000000',
    badgeBackground: '#000000',
    badgeText: '#ffffff',
    iconBoxBackground: '#000000',
    iconColor: '#facc15',
    isDark: false,
  },
  layout: {
    maxWidth: 960,
    topSpacing: 44,
    heroSpacing: 38,
    cardGap: 24,
    cardPadding: 32,
    borderRadius: 20,
    borderWidth: 2,
  },
  cards: {
    borderRadius: 20,
    borderWidth: 2,
    shadow: 'md',
    iconSize: 28,
    hoverLift: true,
  },
  buttons: {
    height: 56,
    borderRadius: 14,
    paddingX: 24,
    arrowStyle: 'classic',
    shadow: 'md',
    hoverEffect: 'scale',
  },
  positions: {
    heroAlign: 'center',
    cardsLayout: 'grid',
    cardsOrder: 'problem_first',
    sectionOrder: 'hero_search_cards',
    buttonsAlign: 'stretch',
    searchPosition: 'above_cards',
    headerLayout: 'standard',
    headerSupplierPosition: 'none',
  },
  content: {
    headerBrandPrefix: 'QUAL',
    headerBrandHighlight: 'A SUA DOR?',
    headerBadgeVisible: true,
    headerBadgeText: '',
    heroBadgeText: 'URGENTE',
    heroBadgeSecondaryText: '1 MIN',
    heroTitlePrefix: '',
    heroTitleHighlight: '',
    heroSubtitle: 'Resolve na hora. Menos texto, mais ação. Sua dor tem prioridade.',
    cardPhysicalTitle: 'Corpo',
    cardPhysicalDesc: 'Muscular, coluna, cabeça. Rápido.',
    cardPhysicalBadge: '',
    cardPhysicalButton: 'AGORA',
    cardProblemTitle: 'Problema',
    cardProblemDesc: 'Carro, casa, rotina. Imediato.',
    cardProblemBadge: '',
    cardProblemButton: 'RESOLVER',
    searchTitle: 'O que precisa resolver?',
    searchSubtitle: '',
    searchPlaceholder: 'Ex: perna traveada, chave perdida, vazamento...',
    searchButtonText: 'IR',
  },
  visibility: {
    showHeaderBrand: true,
    showHeaderBadge: true,
    showHeaderSupplierBtn: false,
    showMascotsGlobal: false,
    showHeroBadge: true,
    showHeroTitle: true,
    showHeroSubtitle: true,
    showCardPhysicalBadge: false,
    showCardProblemBadge: false,
  },
  heroLogo: {
    frameStyle: 'glow',
    size: 220,
    floatingAnimation: true,
    pulseEffect: true,
  },
};

export const TEMPLATE_05_SOFT_HUMAN: ThemeConfig = {
  id: 'soft-human',
  name: 'Soft Human',
  tagline: 'Acolhedor, calmo, tons orgânicos e sensação de escuta atenta',
  description: 'Off-white, cantos orgânicos arredondados, tipografia moderna e agradável para desabafar.',
  version: 1,
  typography: {
    headingFont: 'Poppins',
    bodyFont: 'Plus Jakarta Sans',
    titleDesktopSize: 52,
    titleMobileSize: 36,
    titleWeight: 700,
    titleLineHeight: 1.1,
    titleLetterSpacing: '-0.025em',
    subtitleDesktopSize: 22,
    subtitleMobileSize: 18,
    subtitleWeight: 600,
    subtitleLineHeight: 1.3,
    subtitleLetterSpacing: '-0.01em',
    cardTitleSize: 22,
    cardTitleWeight: 700,
    cardTextSize: 14,
    cardTextWeight: 500,
    cardTextLineHeight: 1.5,
    buttonTextSize: 14,
    buttonTextWeight: 700,
    buttonLetterSpacing: '0em',
    badgeSize: 11,
    badgeWeight: 700,
    footerSize: 12,
  },
  colors: {
    background: '#fbfaf8',
    cardBackground: '#ffffff',
    cardBackgroundHover: '#f5f3ef',
    textPrimary: '#292524',
    textSecondary: '#57534e',
    accent: '#ea580c',
    accentMuted: '#ffedd5',
    buttonBackground: '#292524',
    buttonText: '#ffffff',
    buttonHoverBackground: '#44403c',
    border: '#e7e5e4',
    badgeBackground: '#f5f5f4',
    badgeText: '#44403c',
    iconBoxBackground: '#ffedd5',
    iconColor: '#c2410c',
    isDark: false,
  },
  layout: {
    maxWidth: 900,
    topSpacing: 48,
    heroSpacing: 40,
    cardGap: 24,
    cardPadding: 32,
    borderRadius: 32,
    borderWidth: 1,
  },
  cards: {
    borderRadius: 32,
    borderWidth: 1,
    shadow: 'xs',
    iconSize: 26,
    hoverLift: true,
  },
  buttons: {
    height: 52,
    borderRadius: 26,
    paddingX: 24,
    arrowStyle: 'box',
    shadow: 'xs',
    hoverEffect: 'lift',
  },
  positions: {
    heroAlign: 'center',
    cardsLayout: 'grid',
    cardsOrder: 'physical_first',
    sectionOrder: 'hero_cards_search',
    buttonsAlign: 'stretch',
    searchPosition: 'above_cards',
    headerLayout: 'centered',
    headerSupplierPosition: 'footer_only',
  },
  content: {
    headerBrandPrefix: 'Qual',
    headerBrandHighlight: 'a sua dor?',
    headerBadgeVisible: true,
    headerBadgeText: 'Direto ao ponto',
    heroBadgeText: 'Privado',
    heroBadgeSecondaryText: 'Sem cadastro',
    heroTitlePrefix: '',
    heroTitleHighlight: 'Desabafe',
    heroSubtitle: 'Aqui você pode contar com total naturalidade. Ajudamos com empathia e calma.',
    cardPhysicalTitle: 'Corpo Falando',
    cardPhysicalDesc: 'Conte onde dói, como dói, quando começou. Nós entendemos.',
    cardPhysicalBadge: 'Acolhedor',
    cardPhysicalButton: 'Contar minha dor',
    cardProblemTitle: 'Rotina',
    cardProblemDesc: 'Perdi a chave, pneu furou, vazamento. Conte e resolvemos.',
    cardProblemBadge: 'Empático',
    cardProblemButton: 'Desabafar problema',
    searchTitle: 'Escreva seu problema ou dor',
    searchSubtitle: 'Pode ser qualquer coisa, a gente entende.',
    searchPlaceholder: 'Ex: dor na coluna, cheguei atrasado, encanador...',
    searchButtonText: 'Desabafar',
  },
  visibility: {
    showHeaderBrand: true,
    showHeaderBadge: true,
    showHeaderSupplierBtn: true,
    showMascotsGlobal: true,
    showMascotHero: true,
    showMascotCards: true,
    showHeroBadge: true,
    showHeroTitle: true,
    showHeroSubtitle: true,
  },
  heroLogo: {
    frameStyle: 'circle',
    size: 160,
    floatingAnimation: true,
    pulseEffect: false,
  },
};

export const TEMPLATE_06_DARK_PREMIUM: ThemeConfig = {
  id: 'dark-premium',
  name: 'Dark Premium',
  tagline: 'Elegância noturna, fundo escuro nobre e toques dourados',
  description: 'Interface predominantemente escura com alto contraste de legibilidade sem parecer videogame.',
  version: 1,
  typography: {
    headingFont: 'Manrope',
    bodyFont: 'Plus Jakarta Sans',
    titleDesktopSize: 58,
    titleMobileSize: 38,
    titleWeight: 800,
    titleLineHeight: 1.05,
    titleLetterSpacing: '-0.035em',
    subtitleDesktopSize: 24,
    subtitleMobileSize: 19,
    subtitleWeight: 700,
    subtitleLineHeight: 1.25,
    subtitleLetterSpacing: '-0.02em',
    cardTitleSize: 24,
    cardTitleWeight: 800,
    cardTextSize: 14,
    cardTextWeight: 500,
    cardTextLineHeight: 1.45,
    buttonTextSize: 14,
    buttonTextWeight: 800,
    buttonLetterSpacing: '0em',
    badgeSize: 11,
    badgeWeight: 700,
    footerSize: 12,
  },
  colors: {
    background: '#0c0a09',
    cardBackground: '#1c1917',
    cardBackgroundHover: '#292524',
    textPrimary: '#fafaf9',
    textSecondary: '#a8a29e',
    accent: '#f59e0b',
    accentMuted: '#78350f',
    buttonBackground: '#fafaf9',
    buttonText: '#0c0a09',
    buttonHoverBackground: '#e7e5e4',
    border: '#292524',
    badgeBackground: '#292524',
    badgeText: '#d6d3d1',
    iconBoxBackground: '#292524',
    iconColor: '#fbbf24',
    isDark: true,
  },
  layout: {
    maxWidth: 920,
    topSpacing: 50,
    heroSpacing: 42,
    cardGap: 24,
    cardPadding: 32,
    borderRadius: 24,
    borderWidth: 1,
  },
  cards: {
    borderRadius: 24,
    borderWidth: 1,
    shadow: 'sm',
    iconSize: 26,
    hoverLift: true,
  },
  buttons: {
    height: 52,
    borderRadius: 16,
    paddingX: 22,
    arrowStyle: 'classic',
    shadow: 'sm',
    hoverEffect: 'lift',
  },
  positions: {
    heroAlign: 'left',
    cardsLayout: 'stack',
    cardsOrder: 'problem_first',
    sectionOrder: 'hero_search_cards',
    buttonsAlign: 'left',
    searchPosition: 'above_cards',
    headerLayout: 'minimal',
    headerSupplierPosition: 'none',
  },
  content: {
    headerBrandPrefix: 'QUAL',
    headerBrandHighlight: 'A SUA DOR',
    headerBadgeVisible: false,
    heroBadgeText: 'PREMIUM',
    heroBadgeSecondaryText: '',
    heroTitlePrefix: 'Soluções',
    heroTitleHighlight: 'Premium',
    heroSubtitle: 'Sua dor merece atenção premium. Interface escura, foco total.',
    cardPhysicalTitle: 'Dor Corporal',
    cardPhysicalDesc: 'Muscular, coluna, cabeça. Prioridade premium.',
    cardPhysicalBadge: 'Premium',
    cardPhysicalButton: 'Analisar',
    cardProblemTitle: 'Problema',
    cardProblemDesc: 'Carro, casa, rotina. Solução premium.',
    cardProblemBadge: 'Premium',
    cardProblemButton: 'Resolver',
    searchTitle: 'Busca premium',
    searchSubtitle: 'Digite sua dor ou problema para solução premium.',
    searchPlaceholder: 'Ex: dor no ombro, chave perdida, vazamento...',
    searchButtonText: 'Buscar',
  },
  visibility: {
    showHeaderBrand: true,
    showHeaderBadge: false,
    showHeaderSupplierBtn: false,
    showMascotsGlobal: false,
    showMascotHero: false,
    showMascotCards: false,
    showHeroBadge: true,
    showHeroTitle: true,
    showHeroSubtitle: true,
  },
  heroLogo: {
    frameStyle: 'subtle',
    size: 150,
    floatingAnimation: false,
    pulseEffect: false,
  },
};

export const TEMPLATE_07_SWISS_MODERN: ThemeConfig = {
  id: 'swiss-modern',
  name: 'Swiss Modern',
  tagline: 'Grid rigoroso, alinhamento geométrico e pureza estrutural',
  description: 'Inspirado na escola de design internacional suíça. Ordem, hierarquia direta e clareza impecável.',
  version: 1,
  typography: {
    headingFont: 'Inter',
    bodyFont: 'Inter',
    titleDesktopSize: 54,
    titleMobileSize: 36,
    titleWeight: 900,
    titleLineHeight: 1.04,
    titleLetterSpacing: '-0.04em',
    subtitleDesktopSize: 20,
    subtitleMobileSize: 17,
    subtitleWeight: 600,
    subtitleLineHeight: 1.3,
    subtitleLetterSpacing: '-0.02em',
    cardTitleSize: 22,
    cardTitleWeight: 800,
    cardTextSize: 14,
    cardTextWeight: 500,
    cardTextLineHeight: 1.45,
    buttonTextSize: 13,
    buttonTextWeight: 700,
    buttonLetterSpacing: '0.02em',
    badgeSize: 10,
    badgeWeight: 700,
    footerSize: 11,
  },
  colors: {
    background: '#ffffff',
    cardBackground: '#ffffff',
    cardBackgroundHover: '#f5f5f5',
    textPrimary: '#111111',
    textSecondary: '#666666',
    accent: '#e11d48',
    accentMuted: '#ffe4e6',
    buttonBackground: '#111111',
    buttonText: '#ffffff',
    buttonHoverBackground: '#333333',
    border: '#e5e5e5',
    badgeBackground: '#f0f0f0',
    badgeText: '#333333',
    iconBoxBackground: '#f5f5f5',
    iconColor: '#111111',
    isDark: false,
  },
  layout: {
    maxWidth: 900,
    topSpacing: 48,
    heroSpacing: 40,
    cardGap: 20,
    cardPadding: 32,
    borderRadius: 8,
    borderWidth: 1,
  },
  cards: {
    borderRadius: 8,
    borderWidth: 1,
    shadow: 'none',
    iconSize: 24,
    hoverLift: false,
  },
  buttons: {
    height: 48,
    borderRadius: 6,
    paddingX: 20,
    arrowStyle: 'subtle',
    shadow: 'none',
    hoverEffect: 'darken',
  },
  positions: {
    heroAlign: 'left',
    cardsLayout: 'grid',
    cardsOrder: 'problem_first',
    sectionOrder: 'search_hero_cards',
    buttonsAlign: 'left',
    searchPosition: 'above_cards',
    headerLayout: 'minimal',
    headerSupplierPosition: 'none',
  },
  content: {
    headerBrandPrefix: '',
    headerBrandHighlight: 'DOR?',
    headerBadgeVisible: false,
    heroBadgeText: 'SWISS',
    heroBadgeSecondaryText: '',
    heroTitlePrefix: '',
    heroTitleHighlight: '',
    heroSubtitle: 'Design preciso. Hierarquia clara. Solução direta.',
    cardPhysicalTitle: 'FÍSICA',
    cardPhysicalDesc: 'Corpo e coluna. Diagnóstico objetivo.',
    cardPhysicalBadge: '',
    cardPhysicalButton: 'VER',
    cardProblemTitle: 'PROBLEMA',
    cardProblemDesc: 'Rotina e serviços. Resposta imediata.',
    cardProblemBadge: '',
    cardProblemButton: 'VER',
    searchTitle: 'Busca',
    searchSubtitle: 'Digite ou escolha um caso.',
    searchPlaceholder: 'Ex: dor, chave, pneu...',
    searchButtonText: 'OK',
  },
  visibility: {
    showHeaderBrand: true,
    showHeaderBadge: false,
    showHeaderSupplierBtn: false,
    showMascotsGlobal: false,
    showHeroBadge: true,
    showHeroTitle: true,
    showHeroSubtitle: true,
    showCardPhysicalBadge: false,
    showCardProblemBadge: false,
  },
  heroLogo: {
    frameStyle: 'none',
    size: 120,
    floatingAnimation: false,
    pulseEffect: false,
  },
};

export const TEMPLATE_08_MOBILE_FIRST: ThemeConfig = {
  id: 'mobile-first',
  name: 'Mobile First',
  tagline: 'Otimizado para toque no celular e decisão ultra veloz',
  description: 'Ideal para o passageiro que acaba de escanear o QR Code no banco traseiro do carro. Sem ruído.',
  version: 1,
  typography: {
    headingFont: 'Plus Jakarta Sans',
    bodyFont: 'Plus Jakarta Sans',
    titleDesktopSize: 52,
    titleMobileSize: 42,
    titleWeight: 800,
    titleLineHeight: 1.05,
    titleLetterSpacing: '-0.035em',
    subtitleDesktopSize: 22,
    subtitleMobileSize: 20,
    subtitleWeight: 700,
    subtitleLineHeight: 1.2,
    subtitleLetterSpacing: '-0.02em',
    cardTitleSize: 24,
    cardTitleWeight: 800,
    cardTextSize: 15,
    cardTextWeight: 500,
    cardTextLineHeight: 1.4,
    buttonTextSize: 16,
    buttonTextWeight: 800,
    buttonLetterSpacing: '-0.01em',
    badgeSize: 12,
    badgeWeight: 700,
    footerSize: 12,
  },
  colors: {
    background: '#fafafa',
    cardBackground: '#ffffff',
    cardBackgroundHover: '#f4f4f5',
    textPrimary: '#18181b',
    textSecondary: '#52525b',
    accent: '#f59e0b',
    accentMuted: '#fef3c7',
    buttonBackground: '#18181b',
    buttonText: '#ffffff',
    buttonHoverBackground: '#27272a',
    border: '#e4e4e7',
    badgeBackground: '#f4f4f5',
    badgeText: '#3f3f46',
    iconBoxBackground: '#f4f4f5',
    iconColor: '#18181b',
    isDark: false,
  },
  layout: {
    maxWidth: 840,
    topSpacing: 36,
    heroSpacing: 32,
    cardGap: 20,
    cardPadding: 28,
    borderRadius: 24,
    borderWidth: 1,
  },
  cards: {
    borderRadius: 24,
    borderWidth: 1,
    shadow: 'xs',
    iconSize: 28,
    hoverLift: true,
  },
  buttons: {
    height: 48,
    borderRadius: 6,
    paddingX: 20,
    arrowStyle: 'subtle',
    shadow: 'none',
    hoverEffect: 'darken',
  },
  positions: {
    heroAlign: 'center',
    cardsLayout: 'grid',
    cardsOrder: 'physical_first',
    sectionOrder: 'hero_search_cards',
    buttonsAlign: 'stretch',
    searchPosition: 'above_cards',
    headerLayout: 'minimal',
    headerSupplierPosition: 'none',
  },
  content: {
    headerBrandPrefix: '',
    headerBrandHighlight: 'DOR?',
    headerBadgeVisible: false,
    heroBadgeText: 'RÁPIDO',
    heroBadgeSecondaryText: '100%',
    heroTitlePrefix: '',
    heroTitleHighlight: '',
    heroSubtitle: 'Ultra-rápido. Toque e resolva.',
    cardPhysicalTitle: 'Corpo',
    cardPhysicalDesc: 'Dor física.',
    cardPhysicalBadge: 'Rápido',
    cardPhysicalButton: 'Ir',
    cardProblemTitle: 'Problema',
    cardProblemDesc: 'Dificuldade.',
    cardProblemBadge: 'Rápido',
    cardProblemButton: 'Ir',
    searchTitle: 'Próxima ação',
    searchSubtitle: 'Digite ou escolha:',
    searchPlaceholder: 'Ex: dor, chave, pneu...',
    searchButtonText: 'Ir',
  },
  visibility: {
    showHeaderBrand: true,
    showHeaderBadge: false,
    showHeaderSupplierBtn: false,
    showMascotsGlobal: false,
    showHeroBadge: true,
    showHeroTitle: true,
    showHeroSubtitle: true,
    showCardPhysicalBadge: true,
    showCardProblemBadge: true,
  },
  heroLogo: {
    frameStyle: 'none',
    size: 140,
    floatingAnimation: false,
    pulseEffect: false,
  },
};

export const TEMPLATE_09_PLAYFUL_INTELLIGENT: ThemeConfig = {
  id: 'playful-intelligent',
  name: 'Playful Intelligent',
  tagline: 'Descontraído, inteligente, empático e marcante',
  description: 'Microinterações expressivas, contraste acolhedor, toques de cor inteligentes sem perder a seriedade.',
  version: 1,
  typography: {
    headingFont: 'Outfit',
    bodyFont: 'Plus Jakarta Sans',
    titleDesktopSize: 62,
    titleMobileSize: 40,
    titleWeight: 800,
    titleLineHeight: 1.02,
    titleLetterSpacing: '-0.03em',
    subtitleDesktopSize: 24,
    subtitleMobileSize: 19,
    subtitleWeight: 700,
    subtitleLineHeight: 1.25,
    subtitleLetterSpacing: '-0.015em',
    cardTitleSize: 24,
    cardTitleWeight: 800,
    cardTextSize: 15,
    cardTextWeight: 500,
    cardTextLineHeight: 1.45,
    buttonTextSize: 15,
    buttonTextWeight: 800,
    buttonLetterSpacing: '0em',
    badgeSize: 11,
    badgeWeight: 800,
    footerSize: 12,
  },
  colors: {
    background: '#fbf9f5',
    cardBackground: '#ffffff',
    cardBackgroundHover: '#f8f5ee',
    textPrimary: '#1c1917',
    textSecondary: '#57534e',
    accent: '#d97706',
    accentMuted: '#fef3c7',
    buttonBackground: '#1c1917',
    buttonText: '#ffffff',
    buttonHoverBackground: '#292524',
    border: '#ebe6dd',
    badgeBackground: '#f5efe4',
    badgeText: '#44403c',
    iconBoxBackground: '#fef3c7',
    iconColor: '#b45309',
    isDark: false,
  },
  layout: {
    maxWidth: 940,
    topSpacing: 48,
    heroSpacing: 42,
    cardGap: 24,
    cardPadding: 32,
    borderRadius: 28,
    borderWidth: 1,
  },
  cards: {
    borderRadius: 28,
    borderWidth: 1,
    shadow: 'sm',
    iconSize: 28,
    hoverLift: true,
  },
  buttons: {
    height: 52,
    borderRadius: 20,
    paddingX: 24,
    arrowStyle: 'box',
    shadow: 'sm',
    hoverEffect: 'lift',
  },
  positions: {
    heroAlign: 'center',
    cardsLayout: 'grid',
    cardsOrder: 'problem_first',
    sectionOrder: 'hero_search_cards',
    buttonsAlign: 'center',
    searchPosition: 'above_cards',
    headerLayout: 'centered',
    headerSupplierPosition: 'both',
  },
  content: {
    headerBrandPrefix: 'Qual',
    headerBrandHighlight: 'a sua dor?',
    headerBadgeVisible: true,
    headerBadgeText: 'Inteligente',
    heroBadgeText: 'RAPIDEZ',
    heroBadgeSecondaryText: 'Precisão',
    heroTitlePrefix: '',
    heroTitleHighlight: '',
    heroSubtitle: 'Sua dor não é problema nosso. Soluções práticas, direto ao ponto, com inteligência.',
    cardPhysicalTitle: 'Dor Física',
    cardPhysicalDesc: 'No corpo, muscular, coluna, cabeça. Entendemos e resolvemos.',
    cardPhysicalBadge: 'AI',
    cardPhysicalButton: 'Resolver minha dor',
    cardProblemTitle: 'Dor de Problema',
    cardProblemDesc: 'Dificuldade na vida prática, emergência, carro, casa ou serviço.',
    cardProblemBadge: 'SMART',
    cardProblemButton: 'Resolver meu problema',
    searchTitle: 'O que você precisa resolver agora?',
    searchSubtitle: 'Escreva com suas próprias palavras ou escolha um caso rápido:',
    searchPlaceholder: 'Ex: dor nas costas, perdi a chave, pneu furou...',
    searchButtonText: 'Resolver',
  },
  visibility: {
    showHeaderBrand: true,
    showHeaderBadge: true,
    showHeaderSupplierBtn: true,
    showMascotsGlobal: true,
    showMascotHero: true,
    showMascotCards: true,
    showHeroBadge: true,
    showHeroTitle: true,
    showHeroSubtitle: true,
  },
  heroLogo: {
    frameStyle: 'circle',
    size: 170,
    floatingAnimation: true,
    pulseEffect: true,
  },
};

export const TEMPLATE_10_FUTURE_CLEAN: ThemeConfig = {
  id: 'future-clean',
  name: 'Future Clean',
  tagline: 'Tecnologia de próxima geração, precisão linear e pureza',
  description: 'Tipografia geométrica limpa, microindicadores tecnológicos, alto contraste sem cair em cyberpunk.',
  version: 1,
  typography: {
    headingFont: 'Space Grotesk',
    bodyFont: 'Plus Jakarta Sans',
    titleDesktopSize: 58,
    titleMobileSize: 38,
    titleWeight: 700,
    titleLineHeight: 1.05,
    titleLetterSpacing: '-0.04em',
    subtitleDesktopSize: 22,
    subtitleMobileSize: 18,
    subtitleWeight: 600,
    subtitleLineHeight: 1.3,
    subtitleLetterSpacing: '-0.02em',
    cardTitleSize: 22,
    cardTitleWeight: 700,
    cardTextSize: 14,
    cardTextWeight: 500,
    cardTextLineHeight: 1.45,
    buttonTextSize: 14,
    buttonTextWeight: 700,
    buttonLetterSpacing: '0.02em',
    badgeSize: 11,
    badgeWeight: 700,
    footerSize: 11,
  },
  colors: {
    background: '#090a0f',
    cardBackground: '#12141c',
    cardBackgroundHover: '#181b26',
    textPrimary: '#f8fafc',
    textSecondary: '#94a3b8',
    accent: '#06b6d4',
    accentMuted: '#164e63',
    buttonBackground: '#f8fafc',
    buttonText: '#090a0f',
    buttonHoverBackground: '#e2e8f0',
    border: '#1e2230',
    badgeBackground: '#181b26',
    badgeText: '#cbd5e1',
    iconBoxBackground: '#181b26',
    iconColor: '#22d3ee',
    isDark: true,
  },
  layout: {
    maxWidth: 920,
    topSpacing: 50,
    heroSpacing: 44,
    cardGap: 24,
    cardPadding: 32,
    borderRadius: 16,
    borderWidth: 1,
  },
  cards: {
    borderRadius: 16,
    borderWidth: 1,
    shadow: 'sm',
    iconSize: 26,
    hoverLift: true,
  },
  buttons: {
    height: 50,
    borderRadius: 12,
    paddingX: 22,
    arrowStyle: 'subtle',
    shadow: 'sm',
    hoverEffect: 'lift',
  },
  positions: {
    heroAlign: 'left',
    cardsLayout: 'stack',
    cardsOrder: 'physical_first',
    sectionOrder: 'hero_cards_search',
    buttonsAlign: 'left',
    searchPosition: 'above_cards',
    headerLayout: 'standard',
    headerSupplierPosition: 'none',
  },
  content: {
    headerBrandPrefix: 'QUAL',
    headerBrandHighlight: 'A SUA DOR',
    headerBadgeVisible: true,
    headerBadgeText: '',
    heroBadgeText: 'FUTURO',
    heroBadgeSecondaryText: '01ms',
    heroTitlePrefix: '',
    heroTitleHighlight: '',
    heroSubtitle: 'Precisão linear. Microinterações tecnológicas. Solução em primeira solicitação.',
    cardPhysicalTitle: 'Sensorial',
    cardPhysicalDesc: 'Corpo, muscular, coluna. Sensor inteligente.',
    cardPhysicalBadge: 'LIVE',
    cardPhysicalButton: 'Escanear',
    cardProblemTitle: 'Operacional',
    cardProblemDesc: 'Carro, casa, rotina. Solicitação direta.',
    cardProblemBadge: 'AI',
    cardProblemButton: 'Processar',
    searchTitle: 'Processamento em tempo real',
    searchSubtitle: 'Digite o problema para análise instantânea:',
    searchPlaceholder: 'Ex: dor no ombro, chave perdida, vazamento...',
    searchButtonText: 'Processar',
  },
  visibility: {
    showHeaderBrand: true,
    showHeaderBadge: true,
    showHeaderSupplierBtn: false,
    showMascotsGlobal: false,
    showMascotHero: false,
    showMascotCards: false,
    showHeroBadge: true,
    showHeroTitle: true,
    showHeroSubtitle: true,
  },
  heroLogo: {
    frameStyle: 'glow',
    size: 180,
    floatingAnimation: false,
    pulseEffect: false,
  },
};

export const TEMPLATE_11_CORPORATE_PRO: ThemeConfig = {
  id: 'corporate-pro',
  name: 'Corporate Pro',
  tagline: 'Layout de busca priorizada, cards em pilha e linguagem corporativa direta',
  description: 'Foco em eficiência: a barra de busca vem primeiro, cards são empilhados verticalmente e o texto é objetivo. Ideal para contextos profissionais.',
  version: 1,
  typography: {
    headingFont: 'Inter',
    bodyFont: 'Inter',
    titleDesktopSize: 48,
    titleMobileSize: 32,
    titleWeight: 700,
    titleLineHeight: 1.1,
    titleLetterSpacing: '-0.02em',
    subtitleDesktopSize: 18,
    subtitleMobileSize: 15,
    subtitleWeight: 500,
    subtitleLineHeight: 1.4,
    subtitleLetterSpacing: '-0.01em',
    cardTitleSize: 20,
    cardTitleWeight: 700,
    cardTextSize: 13,
    cardTextWeight: 500,
    cardTextLineHeight: 1.5,
    buttonTextSize: 13,
    buttonTextWeight: 600,
    buttonLetterSpacing: '0.01em',
    badgeSize: 10,
    badgeWeight: 600,
    footerSize: 10,
  },
  colors: {
    background: '#ffffff',
    cardBackground: '#ffffff',
    cardBackgroundHover: '#f8f9fa',
    textPrimary: '#1a1a1a',
    textSecondary: '#666666',
    accent: '#2563eb',
    accentMuted: '#dbeafe',
    buttonBackground: '#1a1a1a',
    buttonText: '#ffffff',
    buttonHoverBackground: '#374151',
    border: '#e5e7eb',
    badgeBackground: '#f1f5f9',
    badgeText: '#334155',
    iconBoxBackground: '#e0f2fe',
    iconColor: '#0369a1',
    isDark: false,
  },
  layout: {
    maxWidth: 800,
    topSpacing: 40,
    heroSpacing: 32,
    cardGap: 16,
    cardPadding: 28,
    borderRadius: 12,
    borderWidth: 1,
    containerPaddingX: 32,
  },
  cards: {
    borderRadius: 12,
    borderWidth: 1,
    shadow: 'xs',
    iconSize: 22,
    hoverLift: true,
  },
  buttons: {
    height: 44,
    borderRadius: 8,
    paddingX: 16,
    arrowStyle: 'subtle',
    shadow: 'none',
    hoverEffect: 'darken',
  },
  positions: {
    heroAlign: 'left',
    cardsLayout: 'stack',
    cardsOrder: 'problem_first',
    sectionOrder: 'search_hero_cards',
    buttonsAlign: 'left',
    searchPosition: 'above_cards',
    headerLayout: 'minimal',
    headerSupplierPosition: 'none',
  },
  content: {
    headerBrandPrefix: 'QUAL',
    headerBrandHighlight: 'A SUA DOR?',
    headerBadgeVisible: false,
    heroBadgeText: '',
    heroTitlePrefix: '',
    heroTitleHighlight: '',
    heroSubtitle: 'Digite seu problema ou dor. Receba orientação objetiva.',
    cardPhysicalTitle: 'Dor Física',
    cardPhysicalDesc: 'Corpo, muscular, coluna, cabeça.',
    cardPhysicalBadge: '',
    cardPhysicalButton: 'Acessar',
    cardProblemTitle: 'Problema',
    cardProblemDesc: 'Carro, casa, rotina.',
    cardProblemBadge: '',
    cardProblemButton: 'Acessar',
    searchTitle: '',
    searchSubtitle: '',
    searchPlaceholder: 'Ex: dor, chave, vazamento...',
    searchButtonText: 'Buscar',
    footerNotice: '© 2026 Qual a sua dor? — Soluções objetivas',
  },
  visibility: {
    showHeaderBrand: true,
    showHeaderBadge: false,
    showHeaderSupplierBtn: false,
    showMascotsGlobal: false,
    showMascotHero: false,
    showMascotCards: false,
    showHeroBadge: false,
    showHeroTitle: true,
    showHeroSubtitle: true,
    showCardPhysicalBadge: false,
    showCardProblemBadge: false,
    showSearchChips: false,
  },
  heroLogo: {
    frameStyle: 'none',
    size: 80,
    floatingAnimation: false,
    pulseEffect: false,
  },
};

export const TEMPLATE_12_MINIMAL_ZEN: ThemeConfig = {
  id: 'minimal-zen',
  name: 'Minimal Zen',
  tagline: 'Máximo em branco, espaço generoso e interação silenciosa',
  description: 'Extrema simplicidade: o app respira espaço em branco, tipografia limpa e interações mínimas. Foco total no conteúdo.',
  version: 1,
  typography: {
    headingFont: 'Inter',
    bodyFont: 'Inter',
    titleDesktopSize: 42,
    titleMobileSize: 28,
    titleWeight: 600,
    titleLineHeight: 1.2,
    titleLetterSpacing: '-0.01em',
    subtitleDesktopSize: 16,
    subtitleMobileSize: 14,
    subtitleWeight: 400,
    subtitleLineHeight: 1.6,
    subtitleLetterSpacing: '0em',
    cardTitleSize: 18,
    cardTitleWeight: 600,
    cardTextSize: 13,
    cardTextWeight: 400,
    cardTextLineHeight: 1.6,
    buttonTextSize: 12,
    buttonTextWeight: 500,
    buttonLetterSpacing: '0.03em',
    badgeSize: 9,
    badgeWeight: 500,
    footerSize: 10,
  },
  colors: {
    background: '#fafafa',
    cardBackground: '#ffffff',
    cardBackgroundHover: '#fafafa',
    textPrimary: '#171717',
    textSecondary: '#737373',
    accent: '#525252',
    accentMuted: '#f5f5f5',
    buttonBackground: '#171717',
    buttonText: '#ffffff',
    buttonHoverBackground: '#262626',
    border: '#eaeaea',
    badgeBackground: '#f5f5f5',
    badgeText: '#525252',
    iconBoxBackground: '#f5f5f5',
    iconColor: '#262626',
    isDark: false,
  },
  layout: {
    maxWidth: 720,
    topSpacing: 72,
    heroSpacing: 48,
    cardGap: 12,
    cardPadding: 24,
    borderRadius: 16,
    borderWidth: 1,
    containerPaddingX: 40,
  },
  cards: {
    borderRadius: 16,
    borderWidth: 1,
    shadow: 'none',
    iconSize: 20,
    hoverLift: false,
  },
  buttons: {
    height: 40,
    borderRadius: 8,
    paddingX: 14,
    arrowStyle: 'none',
    shadow: 'none',
    hoverEffect: 'darken',
  },
  positions: {
    heroAlign: 'center',
    cardsLayout: 'grid',
    cardsOrder: 'physical_first',
    sectionOrder: 'hero_search_cards',
    buttonsAlign: 'center',
    searchPosition: 'above_cards',
    headerLayout: 'minimal',
    headerSupplierPosition: 'none',
  },
  content: {
    headerBrandPrefix: '',
    headerBrandHighlight: 'DOR?',
    headerBadgeVisible: false,
    heroBadgeText: '',
    heroTitlePrefix: '',
    heroTitleHighlight: 'Digite.',
    heroSubtitle: 'Receba solução.',
    cardPhysicalTitle: 'Física',
    cardPhysicalDesc: 'Corpo, coluna, cabeça.',
    cardPhysicalButton: 'Ver',
    cardProblemTitle: 'Problema',
    cardProblemDesc: 'Rotina, serviço.',
    cardProblemButton: 'Ver',
    searchTitle: 'Resolver',
    searchSubtitle: '',
    searchPlaceholder: '...',
    searchButtonText: 'Ir',
    footerNotice: 'Sem complicação.',
  },
  visibility: {
    showHeaderBrand: true,
    showHeaderBadge: false,
    showHeaderSupplierBtn: false,
    showMascotsGlobal: false,
    showMascotHero: false,
    showMascotCards: false,
    showHeroBadge: false,
    showHeroTitle: true,
    showHeroSubtitle: true,
    showCardPhysicalBadge: false,
    showCardProblemBadge: false,
    showSearchChips: false,
  },
  heroLogo: {
    frameStyle: 'none',
    size: 60,
    floatingAnimation: false,
    pulseEffect: false,
  },
};

export const ALL_TEMPLATES: ThemeConfig[] = [
  TEMPLATE_01_UBER_MINIMAL,
  TEMPLATE_02_NEO_STARTUP,
  TEMPLATE_03_EDITORIAL_PREMIUM,
  TEMPLATE_04_BOLD_IMPACT,
  TEMPLATE_05_SOFT_HUMAN,
  TEMPLATE_06_DARK_PREMIUM,
  TEMPLATE_07_SWISS_MODERN,
  TEMPLATE_08_MOBILE_FIRST,
  TEMPLATE_09_PLAYFUL_INTELLIGENT,
  TEMPLATE_10_FUTURE_CLEAN,
  TEMPLATE_11_CORPORATE_PRO,
  TEMPLATE_12_MINIMAL_ZEN,
];

export const DEFAULT_THEME = TEMPLATE_01_UBER_MINIMAL;
