import { ThemeConfig } from './types';

export const TEMPLATE_01_UBER_MINIMAL: ThemeConfig = {
  id: 'uber-minimal',
  name: 'Qual a sua dor? (Oficial)',
  tagline: 'Fundo branco puro, preto profundo e lilás neon vibrante',
  description: 'Identidade visual oficial da marca. Branco puro, botões pretos de alto contraste e destaques em lilás neon.',
  version: 2,
  typography: {
    headingFont: 'Plus Jakarta Sans',
    bodyFont: 'Plus Jakarta Sans',
    titleDesktopSize: 58,
    titleMobileSize: 38,
    titleWeight: 800,
    titleLineHeight: 1.05,
    titleLetterSpacing: '-0.035em',
    subtitleDesktopSize: 22,
    subtitleMobileSize: 18,
    subtitleWeight: 700,
    subtitleLineHeight: 1.25,
    subtitleLetterSpacing: '-0.02em',
    cardTitleSize: 24,
    cardTitleWeight: 800,
    cardTextSize: 14,
    cardTextWeight: 500,
    cardTextLineHeight: 1.45,
    buttonTextSize: 14,
    buttonTextWeight: 700,
    buttonLetterSpacing: '-0.01em',
    badgeSize: 11,
    badgeWeight: 700,
    footerSize: 12,
  },
  colors: {
    background: '#eaf4ff',
    cardBackground: '#ffffff',
    cardBackgroundHover: '#faf5ff',
    textPrimary: '#09090b',
    textSecondary: '#52525b',
    accent: '#a855f7',
    accentMuted: '#f3e8ff',
    buttonBackground: '#09090b',
    buttonText: '#ffffff',
    buttonHoverBackground: '#7e22ce',
    border: '#e4e4e7',
    badgeBackground: '#faf5ff',
    badgeText: '#7c3aed',
    iconBoxBackground: '#09090b',
    iconColor: '#c084fc',
    isDark: false,
  },
  layout: {
    maxWidth: 920,
    topSpacing: 48,
    heroSpacing: 40,
    cardGap: 24,
    cardPadding: 32,
    borderRadius: 24,
    borderWidth: 1,
  },
  cards: {
    borderRadius: 24,
    borderWidth: 1,
    shadow: 'xs',
    iconSize: 26,
    hoverLift: true,
  },
  buttons: {
    height: 52,
    borderRadius: 16,
    paddingX: 20,
    arrowStyle: 'box',
    shadow: 'xs',
    hoverEffect: 'lift',
  },
  positions: {
    heroAlign: 'center',
    cardsLayout: 'grid',
    cardsOrder: 'physical_first',
    sectionOrder: 'hero_search_cards',
    buttonsAlign: 'stretch',
    searchPosition: 'above_cards',
    headerLayout: 'standard',
  },
  content: {
    heroSubtitle: 'Conta pra gente o que está pegando: pode ser uma dor no corpo ou um perrengue do dia a dia. A gente te ajuda a resolver sem enrolação.',
    searchTitle: 'O que você precisa resolver agora?',
    searchSubtitle: 'Escreva com suas próprias palavras ou escolha um caso rápido:',
    searchPlaceholder: 'Ex: dor nas costas, perdi a chave de casa, pneu furou, dentista urgente...',
    searchButtonText: 'Resolver direto',
  },
};

export const TEMPLATE_02_NEO_STARTUP: ThemeConfig = {
  id: 'neo-startup',
  name: 'Neo Startup',
  tagline: 'Visual contemporâneo e dinâmico de tecnologia recente',
  description: 'Grandes títulos, microinterações, tipografia moderna e cards com presença marcante.',
  version: 1,
  typography: {
    headingFont: 'Sora',
    bodyFont: 'Plus Jakarta Sans',
    titleDesktopSize: 64,
    titleMobileSize: 40,
    titleWeight: 800,
    titleLineHeight: 1.02,
    titleLetterSpacing: '-0.04em',
    subtitleDesktopSize: 24,
    subtitleMobileSize: 19,
    subtitleWeight: 700,
    subtitleLineHeight: 1.25,
    subtitleLetterSpacing: '-0.025em',
    cardTitleSize: 26,
    cardTitleWeight: 800,
    cardTextSize: 15,
    cardTextWeight: 500,
    cardTextLineHeight: 1.45,
    buttonTextSize: 15,
    buttonTextWeight: 800,
    buttonLetterSpacing: '0em',
    badgeSize: 11,
    badgeWeight: 800,
    footerSize: 12,
  },
  colors: {
    background: '#f8fafc',
    cardBackground: '#ffffff',
    cardBackgroundHover: '#f1f5f9',
    textPrimary: '#020617',
    textSecondary: '#475569',
    accent: '#3b82f6',
    accentMuted: '#dbeafe',
    buttonBackground: '#020617',
    buttonText: '#ffffff',
    buttonHoverBackground: '#0f172a',
    border: '#e2e8f0',
    badgeBackground: '#f1f5f9',
    badgeText: '#1e293b',
    iconBoxBackground: '#e0f2fe',
    iconColor: '#0284c7',
    isDark: false,
  },
  layout: {
    maxWidth: 960,
    topSpacing: 52,
    heroSpacing: 44,
    cardGap: 24,
    cardPadding: 32,
    borderRadius: 28,
    borderWidth: 1,
  },
  cards: {
    borderRadius: 28,
    borderWidth: 1,
    shadow: 'sm',
    iconSize: 28,
    hoverLift: true,
  },
  buttons: {
    height: 54,
    borderRadius: 18,
    paddingX: 24,
    arrowStyle: 'classic',
    shadow: 'sm',
    hoverEffect: 'lift',
  },
};

export const TEMPLATE_03_EDITORIAL_PREMIUM: ThemeConfig = {
  id: 'editorial-premium',
  name: 'Editorial Premium',
  tagline: 'Refinamento de revista, respiro amplo e precisão estética',
  description: 'Espaço generoso em branco, tipografia elegante sem serifa, composição assimétrica e acabamento nobre.',
  version: 1,
  typography: {
    headingFont: 'DM Sans',
    bodyFont: 'DM Sans',
    titleDesktopSize: 56,
    titleMobileSize: 36,
    titleWeight: 700,
    titleLineHeight: 1.08,
    titleLetterSpacing: '-0.03em',
    subtitleDesktopSize: 22,
    subtitleMobileSize: 18,
    subtitleWeight: 500,
    subtitleLineHeight: 1.35,
    subtitleLetterSpacing: '-0.01em',
    cardTitleSize: 22,
    cardTitleWeight: 700,
    cardTextSize: 14,
    cardTextWeight: 400,
    cardTextLineHeight: 1.55,
    buttonTextSize: 13,
    buttonTextWeight: 600,
    buttonLetterSpacing: '0.04em',
    badgeSize: 11,
    badgeWeight: 600,
    footerSize: 11,
  },
  colors: {
    background: '#fcfbf9',
    cardBackground: '#ffffff',
    cardBackgroundHover: '#fbf8f3',
    textPrimary: '#1a1917',
    textSecondary: '#6e6962',
    accent: '#d97706',
    accentMuted: '#fef3c7',
    buttonBackground: '#1a1917',
    buttonText: '#ffffff',
    buttonHoverBackground: '#2d2b27',
    border: '#edebe8',
    badgeBackground: '#f3efe9',
    badgeText: '#4d4841',
    iconBoxBackground: '#f4ede4',
    iconColor: '#854d0e',
    isDark: false,
  },
  layout: {
    maxWidth: 900,
    topSpacing: 60,
    heroSpacing: 48,
    cardGap: 24,
    cardPadding: 36,
    borderRadius: 20,
    borderWidth: 1,
  },
  cards: {
    borderRadius: 20,
    borderWidth: 1,
    shadow: 'xs',
    iconSize: 24,
    hoverLift: true,
  },
  buttons: {
    height: 48,
    borderRadius: 12,
    paddingX: 20,
    arrowStyle: 'subtle',
    shadow: 'none',
    hoverEffect: 'darken',
  },
};

export const TEMPLATE_04_BOLD_IMPACT: ThemeConfig = {
  id: 'bold-impact',
  name: 'Bold / Impact',
  tagline: 'Títulos enormes, alto contraste e impossível de ignorar',
  description: 'Criado para capturar a atenção imediata, especialmente para motoristas e passageiros escaneando o QR Code.',
  version: 1,
  typography: {
    headingFont: 'Montserrat',
    bodyFont: 'Plus Jakarta Sans',
    titleDesktopSize: 68,
    titleMobileSize: 44,
    titleWeight: 900,
    titleLineHeight: 0.98,
    titleLetterSpacing: '-0.045em',
    subtitleDesktopSize: 26,
    subtitleMobileSize: 20,
    subtitleWeight: 800,
    subtitleLineHeight: 1.2,
    subtitleLetterSpacing: '-0.02em',
    cardTitleSize: 28,
    cardTitleWeight: 900,
    cardTextSize: 15,
    cardTextWeight: 600,
    cardTextLineHeight: 1.4,
    buttonTextSize: 16,
    buttonTextWeight: 900,
    buttonLetterSpacing: '-0.01em',
    badgeSize: 12,
    badgeWeight: 900,
    footerSize: 12,
  },
  colors: {
    background: '#ffffff',
    cardBackground: '#f8f8f8',
    cardBackgroundHover: '#f0f0f0',
    textPrimary: '#000000',
    textSecondary: '#404040',
    accent: '#eab308',
    accentMuted: '#fef9c3',
    buttonBackground: '#000000',
    buttonText: '#ffffff',
    buttonHoverBackground: '#262626',
    border: '#000000',
    badgeBackground: '#000000',
    badgeText: '#ffffff',
    iconBoxBackground: '#000000',
    iconColor: '#facc15',
    isDark: false,
  },
  layout: {
    maxWidth: 960,
    topSpacing: 44,
    heroSpacing: 38,
    cardGap: 24,
    cardPadding: 32,
    borderRadius: 20,
    borderWidth: 2,
  },
  cards: {
    borderRadius: 20,
    borderWidth: 2,
    shadow: 'md',
    iconSize: 28,
    hoverLift: true,
  },
  buttons: {
    height: 56,
    borderRadius: 14,
    paddingX: 24,
    arrowStyle: 'classic',
    shadow: 'md',
    hoverEffect: 'scale',
  },
};

export const TEMPLATE_05_SOFT_HUMAN: ThemeConfig = {
  id: 'soft-human',
  name: 'Soft Human',
  tagline: 'Acolhedor, calmo, tons orgânicos e sensação de escuta atenta',
  description: 'Off-white, cantos orgânicos arredondados, tipografia moderna e agradável para desabafar.',
  version: 1,
  typography: {
    headingFont: 'Poppins',
    bodyFont: 'Plus Jakarta Sans',
    titleDesktopSize: 52,
    titleMobileSize: 36,
    titleWeight: 700,
    titleLineHeight: 1.1,
    titleLetterSpacing: '-0.025em',
    subtitleDesktopSize: 22,
    subtitleMobileSize: 18,
    subtitleWeight: 600,
    subtitleLineHeight: 1.3,
    subtitleLetterSpacing: '-0.01em',
    cardTitleSize: 22,
    cardTitleWeight: 700,
    cardTextSize: 14,
    cardTextWeight: 500,
    cardTextLineHeight: 1.5,
    buttonTextSize: 14,
    buttonTextWeight: 700,
    buttonLetterSpacing: '0em',
    badgeSize: 11,
    badgeWeight: 700,
    footerSize: 12,
  },
  colors: {
    background: '#fbfaf8',
    cardBackground: '#ffffff',
    cardBackgroundHover: '#f5f3ef',
    textPrimary: '#292524',
    textSecondary: '#57534e',
    accent: '#ea580c',
    accentMuted: '#ffedd5',
    buttonBackground: '#292524',
    buttonText: '#ffffff',
    buttonHoverBackground: '#44403c',
    border: '#e7e5e4',
    badgeBackground: '#f5f5f4',
    badgeText: '#44403c',
    iconBoxBackground: '#ffedd5',
    iconColor: '#c2410c',
    isDark: false,
  },
  layout: {
    maxWidth: 900,
    topSpacing: 48,
    heroSpacing: 40,
    cardGap: 24,
    cardPadding: 32,
    borderRadius: 32,
    borderWidth: 1,
  },
  cards: {
    borderRadius: 32,
    borderWidth: 1,
    shadow: 'xs',
    iconSize: 26,
    hoverLift: true,
  },
  buttons: {
    height: 52,
    borderRadius: 26,
    paddingX: 24,
    arrowStyle: 'box',
    shadow: 'xs',
    hoverEffect: 'lift',
  },
};

export const TEMPLATE_06_DARK_PREMIUM: ThemeConfig = {
  id: 'dark-premium',
  name: 'Dark Premium',
  tagline: 'Elegância noturna, fundo escuro nobre e toques dourados',
  description: 'Interface predominantemente escura com alto contraste de legibilidade sem parecer videogame.',
  version: 1,
  typography: {
    headingFont: 'Manrope',
    bodyFont: 'Plus Jakarta Sans',
    titleDesktopSize: 58,
    titleMobileSize: 38,
    titleWeight: 800,
    titleLineHeight: 1.05,
    titleLetterSpacing: '-0.035em',
    subtitleDesktopSize: 24,
    subtitleMobileSize: 19,
    subtitleWeight: 700,
    subtitleLineHeight: 1.25,
    subtitleLetterSpacing: '-0.02em',
    cardTitleSize: 24,
    cardTitleWeight: 800,
    cardTextSize: 14,
    cardTextWeight: 500,
    cardTextLineHeight: 1.45,
    buttonTextSize: 14,
    buttonTextWeight: 800,
    buttonLetterSpacing: '0em',
    badgeSize: 11,
    badgeWeight: 700,
    footerSize: 12,
  },
  colors: {
    background: '#0c0a09',
    cardBackground: '#1c1917',
    cardBackgroundHover: '#292524',
    textPrimary: '#fafaf9',
    textSecondary: '#a8a29e',
    accent: '#f59e0b',
    accentMuted: '#78350f',
    buttonBackground: '#fafaf9',
    buttonText: '#0c0a09',
    buttonHoverBackground: '#e7e5e4',
    border: '#292524',
    badgeBackground: '#292524',
    badgeText: '#d6d3d1',
    iconBoxBackground: '#292524',
    iconColor: '#fbbf24',
    isDark: true,
  },
  layout: {
    maxWidth: 920,
    topSpacing: 50,
    heroSpacing: 42,
    cardGap: 24,
    cardPadding: 32,
    borderRadius: 24,
    borderWidth: 1,
  },
  cards: {
    borderRadius: 24,
    borderWidth: 1,
    shadow: 'sm',
    iconSize: 26,
    hoverLift: true,
  },
  buttons: {
    height: 52,
    borderRadius: 16,
    paddingX: 22,
    arrowStyle: 'classic',
    shadow: 'sm',
    hoverEffect: 'lift',
  },
};

export const TEMPLATE_07_SWISS_MODERN: ThemeConfig = {
  id: 'swiss-modern',
  name: 'Swiss Modern',
  tagline: 'Grid rigoroso, alinhamento geométrico e pureza estrutural',
  description: 'Inspirado na escola de design internacional suíça. Ordem, hierarquia direta e clareza impecável.',
  version: 1,
  typography: {
    headingFont: 'Inter',
    bodyFont: 'Inter',
    titleDesktopSize: 54,
    titleMobileSize: 36,
    titleWeight: 900,
    titleLineHeight: 1.04,
    titleLetterSpacing: '-0.04em',
    subtitleDesktopSize: 20,
    subtitleMobileSize: 17,
    subtitleWeight: 600,
    subtitleLineHeight: 1.3,
    subtitleLetterSpacing: '-0.02em',
    cardTitleSize: 22,
    cardTitleWeight: 800,
    cardTextSize: 14,
    cardTextWeight: 500,
    cardTextLineHeight: 1.45,
    buttonTextSize: 13,
    buttonTextWeight: 700,
    buttonLetterSpacing: '0.02em',
    badgeSize: 10,
    badgeWeight: 700,
    footerSize: 11,
  },
  colors: {
    background: '#ffffff',
    cardBackground: '#ffffff',
    cardBackgroundHover: '#f5f5f5',
    textPrimary: '#111111',
    textSecondary: '#666666',
    accent: '#e11d48',
    accentMuted: '#ffe4e6',
    buttonBackground: '#111111',
    buttonText: '#ffffff',
    buttonHoverBackground: '#333333',
    border: '#e5e5e5',
    badgeBackground: '#f0f0f0',
    badgeText: '#333333',
    iconBoxBackground: '#f5f5f5',
    iconColor: '#111111',
    isDark: false,
  },
  layout: {
    maxWidth: 900,
    topSpacing: 48,
    heroSpacing: 40,
    cardGap: 20,
    cardPadding: 32,
    borderRadius: 8,
    borderWidth: 1,
  },
  cards: {
    borderRadius: 8,
    borderWidth: 1,
    shadow: 'none',
    iconSize: 24,
    hoverLift: false,
  },
  buttons: {
    height: 48,
    borderRadius: 6,
    paddingX: 20,
    arrowStyle: 'subtle',
    shadow: 'none',
    hoverEffect: 'darken',
  },
};

export const TEMPLATE_08_MOBILE_FIRST: ThemeConfig = {
  id: 'mobile-first',
  name: 'Mobile First',
  tagline: 'Otimizado para toque no celular e decisão ultra veloz',
  description: 'Ideal para o passageiro que acaba de escanear o QR Code no banco traseiro do carro. Sem ruído.',
  version: 1,
  typography: {
    headingFont: 'Plus Jakarta Sans',
    bodyFont: 'Plus Jakarta Sans',
    titleDesktopSize: 52,
    titleMobileSize: 42,
    titleWeight: 800,
    titleLineHeight: 1.05,
    titleLetterSpacing: '-0.035em',
    subtitleDesktopSize: 22,
    subtitleMobileSize: 20,
    subtitleWeight: 700,
    subtitleLineHeight: 1.2,
    subtitleLetterSpacing: '-0.02em',
    cardTitleSize: 24,
    cardTitleWeight: 800,
    cardTextSize: 15,
    cardTextWeight: 500,
    cardTextLineHeight: 1.4,
    buttonTextSize: 16,
    buttonTextWeight: 800,
    buttonLetterSpacing: '-0.01em',
    badgeSize: 12,
    badgeWeight: 700,
    footerSize: 12,
  },
  colors: {
    background: '#fafafa',
    cardBackground: '#ffffff',
    cardBackgroundHover: '#f4f4f5',
    textPrimary: '#18181b',
    textSecondary: '#52525b',
    accent: '#f59e0b',
    accentMuted: '#fef3c7',
    buttonBackground: '#18181b',
    buttonText: '#ffffff',
    buttonHoverBackground: '#27272a',
    border: '#e4e4e7',
    badgeBackground: '#f4f4f5',
    badgeText: '#3f3f46',
    iconBoxBackground: '#f4f4f5',
    iconColor: '#18181b',
    isDark: false,
  },
  layout: {
    maxWidth: 840,
    topSpacing: 36,
    heroSpacing: 32,
    cardGap: 20,
    cardPadding: 28,
    borderRadius: 24,
    borderWidth: 1,
  },
  cards: {
    borderRadius: 24,
    borderWidth: 1,
    shadow: 'xs',
    iconSize: 28,
    hoverLift: true,
  },
  buttons: {
    height: 56,
    borderRadius: 18,
    paddingX: 24,
    arrowStyle: 'box',
    shadow: 'xs',
    hoverEffect: 'lift',
  },
};

export const TEMPLATE_09_PLAYFUL_INTELLIGENT: ThemeConfig = {
  id: 'playful-intelligent',
  name: 'Playful Intelligent',
  tagline: 'Descontraído, inteligente, empático e marcante',
  description: 'Microinterações expressivas, contraste acolhedor, toques de cor inteligentes sem perder a seriedade.',
  version: 1,
  typography: {
    headingFont: 'Outfit',
    bodyFont: 'Plus Jakarta Sans',
    titleDesktopSize: 62,
    titleMobileSize: 40,
    titleWeight: 800,
    titleLineHeight: 1.02,
    titleLetterSpacing: '-0.03em',
    subtitleDesktopSize: 24,
    subtitleMobileSize: 19,
    subtitleWeight: 700,
    subtitleLineHeight: 1.25,
    subtitleLetterSpacing: '-0.015em',
    cardTitleSize: 24,
    cardTitleWeight: 800,
    cardTextSize: 15,
    cardTextWeight: 500,
    cardTextLineHeight: 1.45,
    buttonTextSize: 15,
    buttonTextWeight: 800,
    buttonLetterSpacing: '0em',
    badgeSize: 11,
    badgeWeight: 800,
    footerSize: 12,
  },
  colors: {
    background: '#fbf9f5',
    cardBackground: '#ffffff',
    cardBackgroundHover: '#f8f5ee',
    textPrimary: '#1c1917',
    textSecondary: '#57534e',
    accent: '#d97706',
    accentMuted: '#fef3c7',
    buttonBackground: '#1c1917',
    buttonText: '#ffffff',
    buttonHoverBackground: '#292524',
    border: '#ebe6dd',
    badgeBackground: '#f5efe4',
    badgeText: '#44403c',
    iconBoxBackground: '#fef3c7',
    iconColor: '#b45309',
    isDark: false,
  },
  layout: {
    maxWidth: 940,
    topSpacing: 48,
    heroSpacing: 42,
    cardGap: 24,
    cardPadding: 32,
    borderRadius: 28,
    borderWidth: 1,
  },
  cards: {
    borderRadius: 28,
    borderWidth: 1,
    shadow: 'sm',
    iconSize: 28,
    hoverLift: true,
  },
  buttons: {
    height: 52,
    borderRadius: 20,
    paddingX: 24,
    arrowStyle: 'box',
    shadow: 'sm',
    hoverEffect: 'lift',
  },
};

export const TEMPLATE_10_FUTURE_CLEAN: ThemeConfig = {
  id: 'future-clean',
  name: 'Future Clean',
  tagline: 'Tecnologia de próxima geração, precisão linear e pureza',
  description: 'Tipografia geométrica limpa, microindicadores tecnológicos, alto contraste sem cair em cyberpunk.',
  version: 1,
  typography: {
    headingFont: 'Space Grotesk',
    bodyFont: 'Plus Jakarta Sans',
    titleDesktopSize: 58,
    titleMobileSize: 38,
    titleWeight: 700,
    titleLineHeight: 1.05,
    titleLetterSpacing: '-0.04em',
    subtitleDesktopSize: 22,
    subtitleMobileSize: 18,
    subtitleWeight: 600,
    subtitleLineHeight: 1.3,
    subtitleLetterSpacing: '-0.02em',
    cardTitleSize: 22,
    cardTitleWeight: 700,
    cardTextSize: 14,
    cardTextWeight: 500,
    cardTextLineHeight: 1.45,
    buttonTextSize: 14,
    buttonTextWeight: 700,
    buttonLetterSpacing: '0.02em',
    badgeSize: 11,
    badgeWeight: 700,
    footerSize: 11,
  },
  colors: {
    background: '#090a0f',
    cardBackground: '#12141c',
    cardBackgroundHover: '#181b26',
    textPrimary: '#f8fafc',
    textSecondary: '#94a3b8',
    accent: '#06b6d4',
    accentMuted: '#164e63',
    buttonBackground: '#f8fafc',
    buttonText: '#090a0f',
    buttonHoverBackground: '#e2e8f0',
    border: '#1e2230',
    badgeBackground: '#181b26',
    badgeText: '#cbd5e1',
    iconBoxBackground: '#181b26',
    iconColor: '#22d3ee',
    isDark: true,
  },
  layout: {
    maxWidth: 920,
    topSpacing: 50,
    heroSpacing: 44,
    cardGap: 24,
    cardPadding: 32,
    borderRadius: 16,
    borderWidth: 1,
  },
  cards: {
    borderRadius: 16,
    borderWidth: 1,
    shadow: 'sm',
    iconSize: 26,
    hoverLift: true,
  },
  buttons: {
    height: 50,
    borderRadius: 12,
    paddingX: 22,
    arrowStyle: 'subtle',
    shadow: 'sm',
    hoverEffect: 'lift',
  },
};

export const ALL_TEMPLATES: ThemeConfig[] = [
  TEMPLATE_01_UBER_MINIMAL,
  TEMPLATE_02_NEO_STARTUP,
  TEMPLATE_03_EDITORIAL_PREMIUM,
  TEMPLATE_04_BOLD_IMPACT,
  TEMPLATE_05_SOFT_HUMAN,
  TEMPLATE_06_DARK_PREMIUM,
  TEMPLATE_07_SWISS_MODERN,
  TEMPLATE_08_MOBILE_FIRST,
  TEMPLATE_09_PLAYFUL_INTELLIGENT,
  TEMPLATE_10_FUTURE_CLEAN,
];

export const DEFAULT_THEME = TEMPLATE_01_UBER_MINIMAL;
